--- 

- name: Add a user
  hosts: windows
  gather_facts: false
  tasks:
    - name: Add User
      win_user:
        name: test-user-1 
        password: "P@ssw0rd123"
        state: present

    - name: Add User
      win_user:
        name: test-user-2 
        password: "PublicP@ssw0rd123"
        state: present
